import tifa from './assets/imgs/tifa.jpg';
import cloudAndTifa1 from './assets/imgs/cloud-and-tifa-1.jpeg';
import cloudAndTifa2 from './assets/imgs/cloud-and-tifa-2.jpg';
import cloudAndTifa3 from './assets/imgs/cloud-and-tifa-3.jpg';
import cloudAndTifa4 from './assets/imgs/cloud-and-tifa-4.jpg';
import cloudAndTifa5 from './assets/imgs/cloud-and-tifa-5.jpg';
import cloudAndTifa6 from './assets/imgs/cloud-and-tifa-6.jpg';
import cloudAndTifa7 from './assets/imgs/cloud-and-tifa-7.jpg';
import cloudAndTifa8 from './assets/imgs/cloud-and-tifa-8.jpg';
import cloudAndTifa9 from './assets/imgs/cloud-and-tifa-9.jpg';
import cloudAndTifa10 from './assets/imgs/cloud-and-tifa-10.jpg';
import cloudAndTifa11 from './assets/imgs/cloud-and-tifa-11.jpg';

export const imageFolder = [];
imageFolder.push(tifa);
imageFolder.push(cloudAndTifa1);
imageFolder.push(cloudAndTifa2);
imageFolder.push(cloudAndTifa3);
imageFolder.push(cloudAndTifa4);
imageFolder.push(cloudAndTifa5);
imageFolder.push(cloudAndTifa6);
imageFolder.push(cloudAndTifa7);
imageFolder.push(cloudAndTifa8);
imageFolder.push(cloudAndTifa9);
imageFolder.push(cloudAndTifa10);
imageFolder.push(cloudAndTifa11);
